spring.application.name=linde_backend

spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/lindedb?createDatabaseIfNotExist=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update